# Generated by Django 3.0.5 on 2020-04-14 14:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mobile', models.IntegerField()),
                ('emailid', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
            managers=[
                ('user', django.db.models.manager.Manager()),
            ],
        ),
    ]
