# Generated by Django 3.0.5 on 2020-04-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userdetails',
            managers=[
            ],
        ),
    ]
