# Generated by Django 3.0.5 on 2020-04-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200414_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.TextField()),
                ('locality', models.TextField()),
                ('City', models.TextField()),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='relativedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.TextField()),
                ('age', models.IntegerField()),
                ('Bldgrp', models.TextField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='impdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('Bldgrp', models.TextField()),
                ('apartment', models.TextField()),
                ('landmark', models.TextField()),
                ('locality', models.TextField()),
                ('City', models.TextField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_persons', models.IntegerField()),
                ('patient_type', models.TextField()),
                ('date', models.DateField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userdetails')),
            ],
        ),
    ]
