# Generated by Django 3.0.5 on 2020-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200416_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.EmailField(max_length=30),
        ),
    ]
