# Generated by Django 3.0.5 on 2020-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200416_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['no_of_persons']},
        ),
        migrations.AlterModelOptions(
            name='hospital_list',
            options={'ordering': ['hospital_name']},
        ),
        migrations.AlterModelOptions(
            name='impdetails',
            options={'ordering': ['Bldgrp']},
        ),
        migrations.AlterModelOptions(
            name='relativedetails',
            options={'ordering': ['rname']},
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
