# Generated by Django 3.0.5 on 2020-04-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200419_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_list',
            name='userdetails',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.userdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile',
            field=models.IntegerField(max_length=25),
        ),
    ]
