# Generated by Django 3.0.5 on 2020-04-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200419_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital_list',
            name='userdetails',
        ),
        migrations.RemoveField(
            model_name='impdetails',
            name='userdetails',
        ),
        migrations.RemoveField(
            model_name='relativedetails',
            name='userdetails',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='history',
        ),
        migrations.DeleteModel(
            name='hospital_list',
        ),
        migrations.DeleteModel(
            name='impdetails',
        ),
        migrations.DeleteModel(
            name='relativedetails',
        ),
    ]
