# Generated by Django 3.0.5 on 2020-04-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200419_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='emailid',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
    ]
