# Generated by Django 3.0.5 on 2020-04-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20200419_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='emailid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='mobile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='password',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='username',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='relativedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.TextField()),
                ('age', models.IntegerField()),
                ('Bldgrp', models.TextField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userdetails')),
            ],
            options={
                'ordering': ['rname'],
            },
        ),
        migrations.CreateModel(
            name='impdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('Bldgrp', models.TextField()),
                ('apartment', models.TextField()),
                ('landmark', models.TextField()),
                ('locality', models.TextField()),
                ('City', models.TextField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userdetails')),
            ],
            options={
                'ordering': ['Bldgrp'],
            },
        ),
        migrations.CreateModel(
            name='hospital_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.TextField()),
                ('locality', models.TextField()),
                ('City', models.TextField()),
                ('contact', models.IntegerField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userdetails')),
            ],
            options={
                'ordering': ['hospital_name'],
            },
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_persons', models.IntegerField()),
                ('patient_type', models.TextField()),
                ('date', models.DateField()),
                ('userdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.userdetails')),
            ],
            options={
                'ordering': ['no_of_persons'],
            },
        ),
    ]
