# Generated by Django 3.0.5 on 2020-04-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20200419_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='patient_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital_list',
            name='City',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital_list',
            name='hospital_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital_list',
            name='locality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='impdetails',
            name='Bldgrp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='impdetails',
            name='apartment',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='impdetails',
            name='landmark',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='impdetails',
            name='locality',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='relativedetails',
            name='Bldgrp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='relativedetails',
            name='rname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='emailid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
