# Generated by Django 3.0.5 on 2020-04-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200419_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impdetails',
            name='City',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
